all:
  hosts:
    172.31.44.0
    172.31.24.243
  children:
    webservers:
      hosts:
        172.31.44.0
          package_name: ubuntu
          php-modules:
            - php
            - libapache2-mod-php
            - php-mysql
            - php-cli
        172.31.24.243
          package_name: httpd
          php-modules:
            - php
            - php-mysql
