---
- hosts: all
  become: yes
  tasks: 
    - name: install apache
      package: 
        name: "{{ package_name }}"
        state: present
      notify:
        - restart and enable httpd
      when: ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Debian"
    - name: install php modules
      debug:
        var: php-modules
      package:
        name: "{{ item }}"
        state: present
      notify: 
        - restart and enable apache
    when: ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Debian"
    loop: "{{ php-modules }}"
  handlers:
    - name: restart and enable apache
      service:
        name: "{{ package_name }}"
        enabled: yes
        state: restarted 
      when: ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] == "Debian"
